import { z } from 'zod';
import { tool } from 'ai';
import { getLatestResearch, loadRecentDecisions, summarizeRecentDecisions } from '../utils/compaction.js';

/**
 * Create tool to access latest research report
 */
export function createGetResearchTool(agentId) {
  return tool({
    description: 'Get the latest macro market research report generated by the research engine. Contains analysis of current market conditions, trends, and key events.',
    parameters: z.object({}),
    execute: async () => {
      try {
        const research = await getLatestResearch(agentId);
        
        if (!research) {
          return {
            available: false,
            message: 'No research reports available yet. The research engine runs every 12 hours.'
          };
        }
        
        return {
          available: true,
          filename: research.filename,
          content: research.content,
          generatedAt: research.filename.replace('.md', '')
        };
      } catch (error) {
        return {
          available: false,
          error: error.message
        };
      }
    }
  });
}

/**
 * Create tool to access decision history
 */
export function createGetDecisionHistoryTool(agentId) {
  return tool({
    description: 'Get recent trading decisions and their outcomes. Use this to understand past decision patterns and avoid repeating mistakes.',
    parameters: z.object({
      limit: z.number().min(1).max(20).default(5).describe('Number of recent decisions to fetch')
    }),
    execute: async ({ limit }) => {
      try {
        const decisions = await loadRecentDecisions(agentId, limit);
        
        if (decisions.length === 0) {
          return {
            available: false,
            message: 'No decision history available yet.'
          };
        }
        
        const summary = summarizeRecentDecisions(decisions);
        
        return {
          available: true,
          count: decisions.length,
          summary,
          decisions: decisions.map(d => ({
            filename: d.filename,
            timestamp: d.filename.replace('.md', '')
          }))
        };
      } catch (error) {
        return {
          available: false,
          error: error.message
        };
      }
    }
  });
}

/**
 * Create tool to get market news/sentiment (placeholder for future expansion)
 */
export function createGetMarketSentimentTool() {
  return tool({
    description: 'Get current market sentiment indicators and recent news highlights',
    parameters: z.object({
      symbol: z.string().optional().describe('Specific symbol to get sentiment for, or omit for general market')
    }),
    execute: async ({ symbol }) => {
      // This is a placeholder - in production, you'd integrate with news APIs
      // For now, return a structure that the decision agent can work with
      return {
        timestamp: new Date().toISOString(),
        symbol: symbol || 'GENERAL',
        note: 'Market sentiment tool not yet connected to live data. Use research reports for market analysis.',
        placeholder: true
      };
    }
  });
}

export default {
  createGetResearchTool,
  createGetDecisionHistoryTool,
  createGetMarketSentimentTool
};
